// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIC7Z3R_bkxT1wqDwSc5uU8TFqCzU4iDw',
    appId: '1:984471298345:web:390c5c90908b4fe6edd738',
    messagingSenderId: '984471298345',
    projectId: 'templeapp-4655b',
    authDomain: 'templeapp-4655b.firebaseapp.com',
    storageBucket: 'templeapp-4655b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrTjK9R3ftqjv00vUbhq6gmJNHjw2IMJ0',
    appId: '1:984471298345:android:07981153159b2e3dedd738',
    messagingSenderId: '984471298345',
    projectId: 'templeapp-4655b',
    storageBucket: 'templeapp-4655b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmcQ0f7nzLa2sXlBXppPd4OMl3pFR8X50',
    appId: '1:984471298345:ios:d4a43d79485ccc60edd738',
    messagingSenderId: '984471298345',
    projectId: 'templeapp-4655b',
    storageBucket: 'templeapp-4655b.firebasestorage.app',
    iosBundleId: 'com.example.templeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmcQ0f7nzLa2sXlBXppPd4OMl3pFR8X50',
    appId: '1:984471298345:ios:d4a43d79485ccc60edd738',
    messagingSenderId: '984471298345',
    projectId: 'templeapp-4655b',
    storageBucket: 'templeapp-4655b.firebasestorage.app',
    iosBundleId: 'com.example.templeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIC7Z3R_bkxT1wqDwSc5uU8TFqCzU4iDw',
    appId: '1:984471298345:web:d1191ee2e1c0e270edd738',
    messagingSenderId: '984471298345',
    projectId: 'templeapp-4655b',
    authDomain: 'templeapp-4655b.firebaseapp.com',
    storageBucket: 'templeapp-4655b.firebasestorage.app',
  );
}
